### ISSUE TITLE
Remove workflow

### ISSUE THREAD

**Issue by dicook** [nspyrison/cheem_paper#1]
I don't think you need the pages workflow to be active on this repo

**Comment by nspyrison** [comment]
agreed, this option wasn't available: https://docs.github.com/en/actions/managing-workflow-runs/disabling-and-enabling-a-workflow. Do you know what to do?

**Comment by dicook** [comment]
In the Actions tab, there is list of workflows running. You can click on the workflow and delete it.

**Comment by nspyrison** [comment]
I have checked again and still see no such option to delete the `pages-build-deployment` workflow.

**Comment by dicook** [comment]
It might be the Pages link on the Setting menu. There might be a github pages set up to run, that needs to be turned off.

> On 23 Mar 2023, at 9:18 am, Nicholas Spyrison ***@***.***> wrote:
> 
> 
> I see no such option to delete the pages-build-deployment workflow.
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.
> 

cheers,
Di

---
Dianne Cook
***@***.***

**Comment by nspyrison** [comment]
I have unpublished it from the Pages link. Hopefully, that removed the issue.
